/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
    "./index.html",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#7b9cff",
        "tertiary": "#006573",
        "outline": "#73777b",
        "on-secondary": "#e9f4ff",
        "on-primary-fixed": "#000000",
        "on-primary-fixed-variant": "#00266e",
        "tertiary-container": "#3adffa",
        "on-tertiary-fixed-variant": "#005561",
        "surface": "#f3f7fb",
        "inverse-on-surface": "#999da1",
        "surface-container": "#e3e9ee",
        "surface-variant": "#d7dee3",
        "on-surface-variant": "#575c60",
        "surface-bright": "#f3f7fb",
        "primary-fixed-dim": "#658eff",
        "on-secondary-fixed": "#003853",
        "surface-dim": "#ced5db",
        "error-container": "#fb5151",
        "secondary-container": "#a4d8ff",
        "surface-container-highest": "#d7dee3",
        "tertiary-dim": "#005865",
        "inverse-surface": "#0a0f12",
        "surface-container-low": "#ecf1f6",
        "secondary-dim": "#00557b",
        "surface-tint": "#0050d4",
        "on-tertiary-container": "#004b56",
        "on-tertiary-fixed": "#00363e",
        "on-surface": "#2a2f32",
        "error": "#b31b25",
        "secondary": "#00628c",
        "inverse-primary": "#618bff",
        "on-secondary-container": "#004c6f",
        "on-background": "#2a2f32",
        "tertiary-fixed-dim": "#1ad0eb",
        "surface-container-high": "#dde3e8",
        "primary-dim": "#0046bb",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#daf8ff",
        "outline-variant": "#a9aeb1",
        "on-error": "#ffefee",
        "tertiary-fixed": "#3adffa",
        "primary-container": "#7b9cff",
        "background": "#f3f7fb",
        "on-primary-container": "#001e5a",
        "secondary-fixed-dim": "#81ccff",
        "primary": "#0050d4",
        "on-error-container": "#570008",
        "error-dim": "#9f0519",
        "on-primary": "#f1f2ff"
      },
      boxShadow: {
        'floating-sm': '0 4px 20px -2px rgba(0, 80, 212, 0.08), 0 2px 6px -1px rgba(0, 0, 0, 0.04)',
        'floating': '0 20px 40px -15px rgba(0, 80, 212, 0.12), 0 0 1px 1px rgba(255, 255, 255, 0.8)',
        'floating-lg': '0 30px 60px -12px rgba(0, 80, 212, 0.18), 0 18px 36px -18px rgba(0, 0, 0, 0.12)',
        'neon-blue': '0 0 25px -5px rgba(0, 80, 212, 0.5), 0 0 10px -2px rgba(0, 80, 212, 0.3)',
        'neon-teal': '0 0 25px -5px rgba(0, 217, 184, 0.5), 0 0 10px -2px rgba(0, 217, 184, 0.3)',
        'glass-edge': 'inset 0 1px 1px 0 rgba(255, 255, 255, 0.6), 0 10px 30px -10px rgba(0, 0, 0, 0.05)',
      },
      borderRadius: {
        "sm": "0.375rem",
        "DEFAULT": "0.5rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.25rem",
        "2xl": "1.5rem",
        "3xl": "2rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Noto Sans Arabic", "Manrope", "system-ui", "sans-serif"],
        "body": ["Noto Sans Arabic", "Manrope", "system-ui", "sans-serif"],
        "label": ["Noto Sans Arabic", "Manrope", "system-ui", "sans-serif"],
        "manrope": ["Manrope", "sans-serif"]
      },
      animation: {
        'pulse-subtle': 'pulse-subtle 2s ease-in-out infinite',
        'float-slow': 'float 6s ease-in-out infinite',
        'shimmer-sweep': 'shimmerSweep 2s ease-in-out infinite',
        'beacon': 'beaconRing 2s cubic-bezier(0, 0, 0.2, 1) infinite',
      },
      keyframes: {
        'pulse-subtle': {
          '0%, 100%': { opacity: 1 },
          '50%': { opacity: 0.8 },
        },
        'float': {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-6px)' },
        },
        'shimmerSweep': {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        'beaconRing': {
          '0%': { transform: 'scale(0.8)', opacity: '0.9' },
          '70%': { transform: 'scale(2.2)', opacity: '0' },
          '100%': { transform: 'scale(2.2)', opacity: '0' },
        }
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
    require('daisyui'),
  ],
  daisyui: {
    themes: [
      {
        targetLogistics: {
          "primary": "#0050d4",
          "primary-content": "#ffffff",
          "secondary": "#00628c",
          "secondary-content": "#ffffff",
          "accent": "#006573",
          "neutral": "#1a1f23",
          "neutral-content": "#ffffff",
          "base-100": "#ffffff",
          "base-200": "#f3f7fb",
          "base-300": "#e3e9ee",
          "base-content": "#1a1f23",
          "info": "#0284c7",
          "success": "#059669",
          "warning": "#d97706",
          "error": "#dc2626",
        },
        targetLogisticsDark: {
          "primary": "#3b82f6",
          "primary-content": "#ffffff",
          "secondary": "#38bdf8",
          "accent": "#2dd4bf",
          "neutral": "#0f172a",
          "neutral-content": "#ffffff",
          "base-100": "#1e293b",
          "base-200": "#0f172a",
          "base-300": "#334155",
          "base-content": "#f8fafc",
          "info": "#38bdf8",
          "success": "#34d399",
          "warning": "#fbbf24",
          "error": "#f87171",
        },
      },
      "light",
      "dark",
    ],
    darkTheme: "targetLogisticsDark",
    base: true,
    styled: true,
    utils: true,
    logs: false,
  },
}

