import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const enTranslations = {
  // Brand & System
  brand_name: 'Target Logistics',
  brand_tagline: 'From Kuwait to the World',
  ops_suite: 'Operations Suite',

  // Navigation Items
  nav_dashboard: 'Dashboard',
  nav_shipments: 'Shipments',
  nav_organizations: 'Organizations',
  nav_users: 'Users & Access',
  nav_analytics: 'Analytics',
  nav_fleets: 'Fleet Ops',
  nav_warehouse: 'Warehouse & Inventory',
  nav_address_book: 'Address Book',
  nav_whatsapp_logs: 'WhatsApp Logs',
  nav_api_docs: 'API Docs',
  nav_financials: 'Financials',
  nav_settings: 'Settings',

  // Common Actions & Controls
  save_changes: 'Save Changes',
  cancel: 'Cancel',
  close: 'Close',
  confirm: 'Confirm',
  delete: 'Delete',
  edit: 'Edit',
  view_details: 'View Details',
  search: 'Search...',
  search_placeholder: 'Search waybill #, recipient, or phone...',
  search_shipments_placeholder: 'Search tracking #, customer, destination...',
  filter: 'Filter',
  refresh: 'Refresh',
  export_excel: 'Export Excel',
  export_pdf: 'Export PDF',
  collapse_view: 'Collapse View',
  sign_out: 'Sign Out',
  profile: 'My Profile',
  back: 'Back',
  next: 'Next',
  loading: 'Loading...',
  page_of: 'Page',
  of: 'of',
  showing_x_of_y: 'Showing {count} of {total} shipments',
  no_shipments_found: 'No shipments found',
  no_shipments_desc: 'Try clearing your search filter or create a new shipment.',
  loading_manifest: 'Loading consignment manifest...',

  // Filter Tabs
  filter_all: 'All',
  filter_drafts: 'Drafts',
  filter_pending: 'Pending',
  filter_in_transit: 'In Transit',
  filter_delivered: 'Delivered',
  filter_exceptions: 'Exceptions',

  // Table Headers
  th_tracking_service: 'Tracking # / Service',
  th_org_sender: 'Organization / Sender',
  th_route: 'Route (Origin → Dest)',
  th_customer_recipient: 'Customer / Recipient',
  th_status: 'Status',
  th_created: 'Created',
  th_eta: 'ETA',
  th_actions: 'Actions',

  // Action Menu Items
  action_view_details: 'View Details',
  action_view_label: 'View Label',
  action_awb_waybill: 'AWB / Waybill',
  action_invoice_pdf: 'Invoice PDF',
  action_approve_edit: 'Approve / Edit',
  action_delete: 'Delete',

  // Shipments Module
  shipments_title: 'Shipments Management',
  shipments_subtitle: 'Manage consignment lifecycle, track dual-carrier routes, and handle delivery exceptions.',
  new_shipment: 'New Shipment',
  bulk_import_csv: 'Bulk Import CSV',
  waybill_number: 'Waybill #',
  tracking_number: 'Tracking Number',
  recipient: 'Recipient',
  sender: 'Sender / Merchant',
  origin: 'Origin',
  destination: 'Destination',
  carrier: 'Carrier',
  weight: 'Weight (kg)',
  pieces: 'Pieces',
  price: 'Price (KWD)',
  cod_amount: 'Cash on Delivery (COD)',
  created_at: 'Date Created',
  status: 'Status',
  actions: 'Actions',

  // Statuses
  status_draft: 'Draft',
  status_pending: 'Pending Review',
  status_created: 'Consignment Created',
  status_booked: 'Booked',
  status_ready_for_pickup: 'Ready for Pickup',
  status_picked_up: 'Picked Up',
  status_in_transit: 'In Transit',
  status_out_for_delivery: 'Out for Delivery',
  status_delivered: 'Delivered',
  status_returned: 'Returned to Hub',
  status_exception: 'Delivery Exception',
  status_cancelled: 'Cancelled',

  // ETA & Service Names
  eta_today: 'Today',
  eta_hold: 'On Hold',
  eta_delivered: 'Delivered',
  service_express_air: 'Express Air',

  // Kuwaiti Address Terms
  paci_number: 'PACI Civil ID Number',
  area: 'Area / District',
  block: 'Block',
  street: 'Street',
  building: 'Building / House',
  floor: 'Floor',
  unit: 'Flat / Unit',
  delivery_notes: 'Driver Delivery Notes',

  // Bulk Import Modal
  bulk_modal_title: 'Bulk Consignment Batch Ingestion',
  bulk_drop_title: 'Drop your CSV file here, or',
  bulk_browse: 'browse',
  bulk_drop_hint: 'Supports up to 500 orders per batch with automatic address and pricing routing.',
  bulk_paste_title: 'Or Paste CSV Data Directly',
  bulk_parse_btn: 'Parse & Preview →',
  bulk_download_template: 'Download CSV Template',
  bulk_fallback_carrier: 'Fallback Carrier',
  bulk_auto_dispatch: 'Auto-dispatch waybills immediately',
  bulk_import_btn: 'Import Shipments',
  bulk_success_title: 'Batch Ingestion Completed',
  bulk_ready: 'READY',
  bulk_error: 'ERROR',

  // Organizations & B2B
  org_title: 'Organization Management',
  org_subtitle: 'Manage business entities, credit exposure, shared balances, and company member rosters.',
  org_company_entity: 'Company Entity',
  org_type: 'Type',
  org_members: 'Members',
  org_outstanding: 'Outstanding',
  org_available_credit: 'Available Credit',
  org_credit_limit: 'Credit Limit',
  org_new: 'New Organization',
  org_markup_policy: 'Rate Markup & Commercial Pricing Policy',
  org_markup_type: 'Default Markup Model',
  org_percentage_markup: 'Percentage Markup (%)',
  org_flat_surcharge: 'Flat Surcharge (KWD)',
  org_carrier_policy: 'Organization Carrier Access Policy',

  // Finance & Accounts
  finance_title: 'Financial Management & Billing',
  finance_balance: 'Account Balance',
  finance_statement: 'Statement of Account',
  finance_invoices: 'Invoices & Waybills',
  finance_topup: 'Top-up Balance',
  fin_cockpit_title: 'Finance & Ledger Cockpit',
  fin_cockpit_desc: 'Manage customer accounts, track ledger allocations, and visualize cash flow.',
  fin_tab_overview: 'Overview & Cash Flow',
  fin_tab_transactions: 'Ledger Transactions',
  fin_tab_allocations: 'Allocations & Payments',
  fin_tab_invoices: 'Invoices & Billing',
  fin_tab_reports: 'Profitability Reports',
  fin_active_scope: 'Active Ledger Scope',
  fin_realtime_double_entry: 'Real-time double-entry balances',
  fin_solo_shippers: 'Solo Shippers (Unorganized)',
  fin_active_account: 'Active Account / Organization',
  fin_available_balance: 'Available Balance',
  fin_credit_limit: 'Credit Limit',
  fin_unapplied_cash: 'Unapplied Cash',
  fin_unpaid_receivables: 'Total Unpaid Receivables',
  fin_overdue_90: '90+ Days Overdue',
  fin_cash_inflow_trend: 'Cash Inflow & Revenue Trend',
  fin_aging_schedule: 'Aging Receivables Schedule',
  fin_post_adjustment: 'Post Adjustment',
  fin_receive_payment: 'Record Payment',
  fin_auto_allocate: 'Auto-Allocate Oldest',
  fin_filter_all_types: 'All Transaction Types',
  fin_filter_charges: 'Charges (Invoices)',
  fin_filter_payments: 'Payments Received',
  fin_filter_adjustments: 'Adjustments & Credits',
  fin_th_date: 'Date',
  fin_th_type: 'Type',
  fin_th_description: 'Description',
  fin_th_debit: 'Debit (DR)',
  fin_th_credit: 'Credit (CR)',
  fin_th_balance: 'Running Balance',
  fin_th_reference: 'Reference #',
  fin_th_actions: 'Actions',
  fin_th_invoice_num: 'Invoice #',
  fin_th_due_date: 'Due Date',
  fin_th_amount: 'Total Amount',
  fin_th_paid: 'Paid Amount',
  fin_th_remaining: 'Remaining',
  fin_th_status: 'Status',
  fin_export_statement: 'Export Statement (PDF)',
  fin_download_invoice: 'Download Invoice',
  fin_no_transactions: 'No ledger transactions recorded for this scope.',
  fin_no_invoices: 'No invoices generated yet.',
  fin_outstanding_balance: 'Outstanding Balance',
  fin_customer_statement: 'Customer Statement of Account',
  
  // Shipment Route & Details
  origin_label: 'Origin',
  destination_label: 'Destination',
  shipper_from: 'Shipper (From)',
  consignee_to: 'Consignee (To)',
  route_connector: 'Route',
  copy_tracking_link: 'Copy Link',
  approve_book_carrier: 'Approve & Book Carrier',
  re_dispatch_carrier: 'Re-Dispatch Carrier',
  convert_to_carrier: 'Convert to Carrier',
  capture_pod: 'Capture POD',
  customer_return: 'Customer Return',
  edit_consignment: 'Edit Consignment',
  delete_shipment: 'Delete',
  package_structure: 'Package & Consignment Structure',
  edit_parcels: 'Edit Parcels',
  actual_weight: 'Actual Weight',
  total_pieces: 'Total Pieces',
  packaging_type: 'Packaging',
  incoterm_label: 'Incoterm',
  dangerous_goods_regulated: 'Regulated Dangerous Goods (IATA / DGR)',
  dgr_hazard_warning: 'DGR Hazard',
  sandbox_test_mode: 'Test API Sandbox Active',
  live_prod_mode: 'Live Production API',
  back_to_shipments: 'Shipments',
  consignment_details: 'Consignment Details',
  last_updated: 'Last Updated',
  dim_weight_kg: 'Dim Weight (kg)',
  package_dim_cm: 'Dimensions (cm)',
  pkg_description: 'Goods Description',
  pkg_quantity: 'Qty',
  item_val: 'Declared Value',

  // Dashboard Telemetry & KPI Cockpit
  dash_hello: 'Hello,',
  dash_subtitle: 'Target Logistics Global Operations Cockpit & Telemetry',
  dash_support: 'Support',
  dash_create_shipment: 'Create Shipment',
  dash_total_shipments: 'Total Shipments',
  dash_total_desc: 'Total active lifecycle',
  dash_pending_gate: 'Pending Gate',
  dash_pending_desc: 'Awaiting manifest approval',
  dash_global_transit: 'Global Transit',
  dash_transit_desc: 'Cross-border movement',
  dash_exceptions: 'Critical Exceptions',
  dash_exceptions_desc: 'Requires intervention',
  dash_success_rate: 'Success Rate',
  dash_success_desc: 'Successfully delivered',
  units: 'units',
  stable: 'Stable',
  dash_throughput_title: 'Global Throughput Volume',
  dash_throughput_desc: 'Cargo volume distribution across international dispatch hubs',
  weekly: 'Weekly',
  monthly: 'Monthly',
  dash_dispatch_performance: 'Dispatch Performance',
  dash_kvi_subtitle: 'Key Velocity Indicators (KVI)',
  dash_carrier_response: 'Carrier Response Rate',
  dash_air_punctuality: 'Air-Freight Punctuality',
  dash_customs_avg: 'Customs Clearance avg.',
  dash_client_nps: 'Client Satisfaction (NPS)',
  dash_forecast_title: 'Forecast',
  dash_forecast_desc: '+15% Volume projected next week (~340 pkgs)',
  dash_live_feed_title: 'Live Operations Feed',
  dash_live_feed_desc: 'Real-time network events & dispatches',
  // Kinetic Wizard & Edit Mode
  wizard_title_new: 'Create Kinetic Consignment',
  wizard_title_edit: 'Edit Consignment & Review',
  wizard_subtitle: 'Configure international freight route, cargo specs, and select optimal carrier rates.',
  step_origin_sender: 'Origin & Sender',
  step_destination_receiver: 'Destination & Receiver',
  step_cargo_parcels: 'Parcels & Cargo',
  step_carrier_rates: 'Carrier & Rates',
  step_review_dispatch: 'Review & Dispatch',
  sender_merchant_name: 'Sender / Merchant Name',
  sender_phone: 'Sender Phone',
  sender_address: 'Sender Pickup Address',
  receiver_name: 'Receiver Full Name',
  receiver_phone: 'Receiver Mobile (WhatsApp)',
  receiver_paci: 'PACI Civil ID Number',
  receiver_area: 'Area / District',
  receiver_block: 'Block',
  receiver_street: 'Street',
  receiver_building: 'Building / House',
  receiver_floor: 'Floor',
  receiver_unit: 'Flat / Unit',
  driver_notes: 'Driver Delivery Notes',
  parcels_count: 'Number of Parcels',
  package_weight: 'Total Weight (kg)',
  package_dimensions: 'Dimensions (L x W x H cm)',
  declared_value: 'Declared Goods Value',
  cod_amount_label: 'Cash on Delivery Amount (COD)',
  dangerous_goods: 'Contains Hazardous / Dangerous Goods',
  select_carrier_title: 'Select Dispatch Carrier & Service',
  estimated_transit_time: 'Estimated Transit Time',
  shipping_cost: 'Shipping Cost',
  total_payable: 'Total Payable Amount',
  btn_next_step: 'Next Step →',
  btn_prev_step: '← Previous',
  btn_create_shipment: 'Confirm & Create Shipment',
  btn_save_changes: 'Save Changes',
  btn_approve_shipment: 'Approve & Dispatch',

  details_title: 'Consignment Details',
  timeline_title: 'Live Tracking Timeline',
  btn_print_label: 'Print Waybill Label',
  btn_download_invoice: 'Download Invoice',
  btn_send_whatsapp: 'Send WhatsApp Notification',
  btn_share_tracking: 'Share Tracking Link',
  btn_update_status: 'Update Status',
  btn_request_location_otp: 'Request Receiver Location (OTP)',
  otp_modal_title: 'Receiver Secure Location Assistant',
  otp_modal_desc: 'Send a one-time passcode to the receiver phone to verify identity and enable pin-drop location assistance.',
  audit_log_title: 'Operational Audit Log',
  audit_log_desc: 'Chronological log of all modifications, address updates, and approvals.',

  // Finance Reports & Analytics
  rep_cogs_title: 'Carrier COGS & Shipment Profitability',
  rep_cogs_desc: 'Real-time double-entry margin analysis comparing wholesale carrier cost vs. billed revenue.',
  rep_total_revenue: 'Total Billed Revenue',
  rep_wholesale_cost: 'Wholesale Carrier Cost (COGS)',
  rep_net_gross_profit: 'Net Gross Profit',
  rep_overall_margin: 'Overall Gross Margin',
  rep_tracking: 'Tracking',
  rep_carrier: 'Carrier',
  rep_date: 'Date',
  rep_customer: 'Customer',
  rep_cost: 'Wholesale Cost',
  rep_revenue: 'Billed Revenue',
  rep_profit: 'Gross Profit',
  rep_margin_pct: 'Margin %',
  rep_payment: 'Payment',
  rep_paid: 'PAID',
  rep_unpaid: 'UNPAID',
  rep_cod_title: 'Driver Cash-on-Delivery (COD) Clearing',
  rep_cod_desc: 'Track cash collected by drivers upon delivery and reconcile hub vault handovers.',
  rep_unremitted_shipments: 'Unremitted COD Shipments',
  rep_unremitted_cash: 'Unremitted Cash',
  rep_driver: 'Driver',
  rep_cod_amount: 'COD Amount',
  rep_delivery_status: 'Delivery Status',
  rep_cod_clearing_status: 'COD Clearing Status',
  rep_daily_rev_title: 'Daily Invoiced Revenue & Collections',
  rep_invoiced_charges: 'Invoiced Charges',
  rep_payments_collected: 'Payments Collected',
  rep_client_org_balances: 'Client & Organization Balances',
  rep_credit_limit: 'Credit Limit',
  rep_current_balance: 'Current Balance',
  rep_unapplied_cash: 'Unapplied Cash',
  rep_fx_title: 'Multi-Currency Exchange Rates & Conversion Engine',
  rep_fx_desc: 'Base Reference Currency: Kuwaiti Dinar (KWD). Used for automated invoice settlement, carrier liabilities, and foreign exchange reporting.',
  rep_live_fx_calc: 'Live FX Calculator',
  rep_currency_code: 'Currency Code',
  rep_currency_name: 'Currency Name',
  rep_rate_in_kwd: 'Rate in KWD (1 Unit =)',
  rep_kwd_parity: 'KWD Parity (1 KWD =)',
  rep_reconciliation_title: 'Carrier Invoice Reconciliation',
  rep_reconciliation_desc: 'Upload or paste carrier billing invoices (DHL, LogesTechs, OTE, DGR) to audit wholesale costs and post adjustments.',
  rep_select_carrier: 'Select Carrier',
  rep_upload_csv: 'Upload CSV Invoice',
  rep_audit_btn: 'Audit & Match Records',
  rep_auditing: 'Auditing Invoices...',
  rep_paste_csv_title: 'Or Paste CSV Data',
  rep_carrier_billed: 'Total Carrier Billed',
  rep_internal_cost: 'Internal Expected Cost',
  rep_cost_variance: 'Total Cost Variance',
  rep_discrepancies: 'Discrepancies / Unmatched',
  rep_post_adjustments: 'Post Adjustments',
  rep_posting: 'Posting...',
  rep_audit_notes: 'Audit Notes',
  rep_tab_profitability: 'Shipment Profitability & COGS',
  rep_tab_reconciliation: 'Carrier Reconciliation',
  rep_tab_cod: 'Driver COD Clearing',
  rep_tab_revenue: 'Revenue & Collections',
  rep_tab_balances: 'Organization Balances',
  rep_tab_rates: 'Multi-Currency FX Rates',

  // Shipment Details Sub-components
  tab_overview: 'Overview',
  tab_parcels: 'Parcels & Items',
  tab_activity: 'Live Activity',
  tab_management: 'Operations & Management',
  origin_sender: 'Origin (Sender)',
  destination_recipient: 'Destination (Recipient)',
  service_type: 'Service Type',
  current_location: 'Current Location',
  share_live_location: 'Share Live Location',
  generated_documents: 'Generated Documents',
  target_label: 'Target Label',
  system_label_qr: 'System Label with QR code',
  carrier_awb: 'Carrier AWB',
  commercial_invoice: 'Commercial Invoice',
  customs_declaration: 'Customs Declaration',
  delivery_progress: 'Delivery Progress',
  sales_price: 'Sales Price',
  cost_price: 'Cost Price',
  pricing_policy_source: 'Pricing Policy Source',
  internal_notes: 'Internal Notes',
  update_location_manually: 'Update Location Manually'
};

const arTranslations = {
  // Brand & System (Kuwaiti Business Terms)
  brand_name: 'تارجت للخدمات اللوجستية',
  brand_tagline: 'من الكويت إلى العالم',
  ops_suite: 'منظومة العمليات التشغيلية',

  // Navigation Items
  nav_dashboard: 'لوحة التحكم',
  nav_shipments: 'الشحنات والطرود',
  nav_organizations: 'الشركات والمؤسسات',
  nav_users: 'المستخدمين والصلاحيات',
  nav_analytics: 'المؤشرات والتقارير',
  nav_fleets: 'أسطول التوصيل والمناديب',
  nav_warehouse: 'المستودع والجرد (الشويخ)',
  nav_address_book: 'دفتر العناوين',
  nav_whatsapp_logs: 'سجلات الواتساب',
  nav_api_docs: 'دليل الربط والمطورين (API)',
  nav_financials: 'المالية وكشف الحساب',
  nav_settings: 'إعدادات النظام',

  // Common Actions & Controls
  save_changes: 'حفظ التغييرات',
  cancel: 'إلغاء',
  close: 'إغلاق',
  confirm: 'تأكيد العملية',
  delete: 'حذف',
  edit: 'تعديل',
  view_details: 'عرض التفاصيل',
  search: 'بحث...',
  search_placeholder: 'بحث برقم البوليصة، اسم المستلم، أو رقم الهاتف...',
  search_shipments_placeholder: 'بحث برقم الشحنة، المستلم، أو الوجهة...',
  filter: 'تصفية',
  refresh: 'تحديث البيانات',
  export_excel: 'تصدير إكسل',
  export_pdf: 'تصدير PDF',
  collapse_view: 'طي القائمة',
  sign_out: 'تسجيل الخروج',
  profile: 'الملف الشخصي',
  back: 'رجوع',
  next: 'التالي',
  loading: 'جاري التحميل...',
  page_of: 'صفحة',
  of: 'من أصل',
  showing_x_of_y: 'عرض {count} من إجمالي {total} شحنة',
  no_shipments_found: 'لا توجد شحنات مطابقة',
  no_shipments_desc: 'جرّب تغيير معايير البحث أو أنشئ شحنة جديدة.',
  loading_manifest: 'جاري تحميل مانيفست وبوالص الشحن...',

  // Filter Tabs
  filter_all: 'الكل',
  filter_drafts: 'المسودات',
  filter_pending: 'بانتظار الموافقة',
  filter_in_transit: 'قيد النقل والشحن',
  filter_delivered: 'تم التسليم',
  filter_exceptions: 'تعذر التسليم',

  // Table Headers
  th_tracking_service: 'رقم الشحنة / نوع الخدمة',
  th_org_sender: 'الشركة / الراسل',
  th_route: 'المسار (المصدر ← الوجهة)',
  th_customer_recipient: 'المستلم والعميل',
  th_status: 'الحالة',
  th_created: 'تاريخ الإنشاء',
  th_eta: 'الموعد المتوقع',
  th_actions: 'الإجراءات',

  // Action Menu Items
  action_view_details: 'عرض التفاصيل',
  action_view_label: 'عرض وطباعة البوليصة',
  action_awb_waybill: 'بوليصة الشحن (AWB)',
  action_invoice_pdf: 'تحميل فاتورة PDF',
  action_approve_edit: 'اعتماد / تعديل',
  action_delete: 'حذف الشحنة',

  // Shipments Module
  shipments_title: 'إدارة الشحنات والبوالص',
  shipments_subtitle: 'متابعة دورة حياة الشحنات، إدارة شركات النقل، ومعالجة تعذر التسليم.',
  new_shipment: 'إنشاء شحنة جديدة',
  bulk_import_csv: 'استيراد شحنات بالجملة (CSV)',
  waybill_number: 'رقم بوليصة الشحن',
  tracking_number: 'رقم التتبع (AWB)',
  recipient: 'المستلم',
  sender: 'الراسل / التاجر',
  origin: 'مكان الاستلام (الراسل)',
  destination: 'وجهة التسليم',
  carrier: 'شركة الشحن',
  weight: 'الوزن (كجم)',
  pieces: 'عدد القطع',
  price: 'سعر الشحن (د.ك)',
  cod_amount: 'التحصيل عند الاستلام (COD)',
  created_at: 'تاريخ الإنشاء',
  status: 'حالة الشحنة',
  actions: 'الإجراءات',

  // Statuses (Kuwaiti Logistics Terminology)
  status_draft: 'مسودة',
  status_pending: 'قيد التجهيز والمراجعة',
  status_created: 'تم إصدار البوليصة',
  status_booked: 'تم حجز الشحنة',
  status_ready_for_pickup: 'جاهز للاستلام من التاجر',
  status_picked_up: 'تم الاستلام من المصدر',
  status_in_transit: 'قيد النقل للشحن الخارجي',
  status_out_for_delivery: 'مع المندوب للتسليم',
  status_delivered: 'تم التسليم بنجاح',
  status_returned: 'مرتجع للمستودع',
  status_exception: 'تعذر التسليم / استثناء',
  status_cancelled: 'ملغاة',

  // ETA & Service Names
  eta_today: 'اليوم',
  eta_hold: 'معلق',
  eta_delivered: 'تم التسليم',
  service_express_air: 'شحن جوي سريع',

  // Kuwaiti Address Terms
  paci_number: 'الرقم الآلي للعنوان (PACI)',
  area: 'المنطقة',
  block: 'القطعة',
  street: 'الشارع',
  building: 'القسيمة / المبنى',
  floor: 'الدور',
  unit: 'الشقة / المكتب',
  delivery_notes: 'ملاحظات خاصة للمندوب',

  // Bulk Import Modal
  bulk_modal_title: 'استيراد بوالص الشحن بالجملة',
  bulk_drop_title: 'اسحب ملف الإكسل أو الـ CSV هنا، أو',
  bulk_browse: 'تصفح جهازك',
  bulk_drop_hint: 'يدعم حتى 500 شحنة بالدفعة الواحدة مع احتساب الأسعار والتحقق التلقائي من العناوين.',
  bulk_paste_title: 'أو الصق بيانات الـ CSV مباشرة',
  bulk_parse_btn: 'معالجة وعرض البيانات ←',
  bulk_download_template: 'تحميل نموذج CSV الجاهز',
  bulk_fallback_carrier: 'شركة الشحن الافتراضية',
  bulk_auto_dispatch: 'ترحيل وإصدار البوالص تلقائياً فور الاستيراد',
  bulk_import_btn: 'استيراد وبدء المعالجة',
  bulk_success_title: 'تم استيراد الدفعة بنجاح',
  bulk_ready: 'جاهز للإصدار',
  bulk_error: 'يوجد خطأ',

  // Organizations & B2B
  org_title: 'إدارة الشركات والمتاجر',
  org_subtitle: 'إدارة حسابات الشركات والعملاء، حدود الائتمان، والأرصدة المشتركة.',
  org_company_entity: 'اسم الشركة / المتجر',
  org_type: 'نوع الحساب',
  org_members: 'الأعضاء والمستخدمين',
  org_outstanding: 'المستحقات المطلوبة',
  org_available_credit: 'الرصيد الائتماني المتاح',
  org_credit_limit: 'الحد الائتماني المعتمد',
  org_new: 'إضافة شركة جديدة',
  org_markup_policy: 'سياسة هامش الربح والتعرفة الجمركية',
  org_markup_type: 'نموذج احتساب الربح',
  org_percentage_markup: 'نسبة الإضافة المئوية (%)',
  org_flat_surcharge: 'مبلغ إضافي ثابت (د.ك)',
  org_carrier_policy: 'شركات الشحن المعتمدة للشركة',

  // Finance & Accounts (Kuwaiti Business & Accounting Terminology)
  finance_title: 'المالية والحسابات',
  finance_balance: 'الرصيد المالي',
  finance_statement: 'كشف حساب العميل',
  finance_invoices: 'الفواتير وبوالص الشحن',
  finance_topup: 'إيداع رصيد / تسوية',
  fin_cockpit_title: 'لوحة التحكم المالية ودفتر الأستاذ',
  fin_cockpit_desc: 'إدارة حسابات الشركات والعملاء، تتبع قيود التسوية، ومراقبة التدفق النقدي.',
  fin_tab_overview: 'نظرة عامة والتدفق النقدي',
  fin_tab_transactions: 'القيود وسجل المعاملات',
  fin_tab_allocations: 'الدفعات وتسوية الفواتير',
  fin_tab_invoices: 'الفواتير والمطالبات',
  fin_tab_reports: 'تقارير الأرباح والإيرادات',
  fin_active_scope: 'نطاق الحساب النشط',
  fin_realtime_double_entry: 'أرصدة فورية بنظام القيد المزدوج',
  fin_solo_shippers: 'شاحنون أفراد (بدون شركة)',
  fin_active_account: 'الحساب / الشركة المحددة',
  fin_available_balance: 'الرصيد المتاح',
  fin_credit_limit: 'الحد الائتماني',
  fin_unapplied_cash: 'دفعات غير مسواة',
  fin_unpaid_receivables: 'إجمالي المستحقات غير المحصلة',
  fin_overdue_90: 'متأخرات أكثر من 90 يوم',
  fin_cash_inflow_trend: 'حركة التدفق النقدي والإيرادات',
  fin_aging_schedule: 'جدول أعمار الديون والمستحقات',
  fin_post_adjustment: 'تسجيل قيد تسوية',
  fin_receive_payment: 'تسجيل دفعة / قبض',
  fin_auto_allocate: 'تسوية تلقائية لأقدم الفواتير',
  fin_filter_all_types: 'جميع أنواع القيود',
  fin_filter_charges: 'رسوم الشحن (الفواتير)',
  fin_filter_payments: 'الدفعات المستلمة',
  fin_filter_adjustments: 'التسويات والخصومات',
  fin_th_date: 'التاريخ',
  fin_th_type: 'نوع القيد',
  fin_th_description: 'البيان / الشرح',
  fin_th_debit: 'مدين (DR)',
  fin_th_credit: 'دائن (CR)',
  fin_th_balance: 'الرصيد التراكمي',
  fin_th_reference: 'رقم المرجع',
  fin_th_actions: 'الإجراءات',
  fin_th_invoice_num: 'رقم الفاتورة',
  fin_th_due_date: 'تاريخ الاستحقاق',
  fin_th_amount: 'المبلغ الإجمالي',
  fin_th_paid: 'المبلغ المدفوع',
  fin_th_remaining: 'المتبقي',
  fin_th_status: 'الحالة',
  fin_export_statement: 'تصدير كشف حساب (PDF)',
  fin_download_invoice: 'تحميل الفاتورة PDF',
  fin_no_transactions: 'لا توجد قيود مسجلة في هذا النطاق.',
  fin_no_invoices: 'لا توجد فواتير صادرة حتى الآن.',
  fin_outstanding_balance: 'الرصيد المستحق',
  fin_customer_statement: 'كشف حساب العميل المالي',
  
  // Shipment Route & Details (Kuwaiti Logistics Terminology)
  origin_label: 'المصدر',
  destination_label: 'الوجهة',
  shipper_from: 'الراسل / المصدر (من)',
  consignee_to: 'المستلم / الوجهة (إلى)',
  route_connector: 'المسار',
  copy_tracking_link: 'نسخ رابط التتبع',
  approve_book_carrier: 'اعتماد وحجز شركة الشحن',
  re_dispatch_carrier: 'إعادة ترحيل للناقل',
  convert_to_carrier: 'تحويل لشركة شحن خارجية',
  capture_pod: 'تسجيل إثبات التسليم (POD)',
  customer_return: 'طلب إرجاع الشحنة',
  edit_consignment: 'تعديل بيانات البوليصة',
  delete_shipment: 'حذف الشحنة',
  package_structure: 'مواصفات الطرود ومحتويات الشحنة',
  edit_parcels: 'تعديل الطرود',
  actual_weight: 'الوزن الفعلي',
  total_pieces: 'إجمالي القطع',
  packaging_type: 'نوع التغليف',
  incoterm_label: 'شرط الشحن (Incoterm)',
  dangerous_goods_regulated: 'بضائع خطرة خاضعة للوائح الشحن الجوي (IATA / DGR)',
  dgr_hazard_warning: 'مواد خطرة (DGR)',
  sandbox_test_mode: 'بيئة الاختبار التجريبية (Sandbox)',
  live_prod_mode: 'بيئة التشغيل المباشرة',
  back_to_shipments: 'الشحنات والطرود',
  consignment_details: 'تفاصيل بوليصة الشحن',
  last_updated: 'آخر تحديث',
  dim_weight_kg: 'الوزن الحجمي (كجم)',
  package_dim_cm: 'الأبعاد (سم)',
  pkg_description: 'وصف البضاعة',
  pkg_quantity: 'العدد',
  item_val: 'القيمة المصرح عنها',

  // Dashboard Telemetry & KPI Cockpit (Kuwaiti Business Terms)
  dash_hello: 'مرحباً،',
  dash_subtitle: 'لوحة التحكم التشغيلية والرصد المباشر لشبكة تارجت اللوجستية',
  dash_support: 'الدعم الفني',
  dash_create_shipment: 'إنشاء شحنة +',
  dash_total_shipments: 'إجمالي الشحنات',
  dash_total_desc: 'إجمالي دورة العمليات النشطة',
  dash_pending_gate: 'بانتظار الموافقة والترحيل',
  dash_pending_desc: 'بانتظار اعتماد المانيفست',
  dash_global_transit: 'شحنات قيد النقل الدولي',
  dash_transit_desc: 'نقل وشحن دولي ومحلي',
  dash_exceptions: 'حالات استثنائية وتعذر تسليم',
  dash_exceptions_desc: 'تتطلب تدخل ومتابعة المندوب',
  dash_success_rate: 'نسبة نجاح التسليم',
  dash_success_desc: 'تم التسليم بنجاح للعميل',
  units: 'شحنة',
  stable: 'مستقر',
  dash_throughput_title: 'حجم الشحنات المنقولة',
  dash_throughput_desc: 'توزيع حركة الطرود عبر محطات ومستودعات التوزيع',
  weekly: 'أسبوعي',
  monthly: 'شهري',
  dash_dispatch_performance: 'أداء التوزيع والعمليات',
  dash_kvi_subtitle: 'مؤشرات سرعة الإنجاز وجودة الخدمة (KVI)',
  dash_carrier_response: 'سرعة استجابة شركة الشحن',
  dash_air_punctuality: 'دقة مواعيد الشحن الجوي',
  dash_customs_avg: 'متوسط مدة التخليص الجمركي',
  dash_client_nps: 'مستوى رضا العملاء (NPS)',
  dash_forecast_title: 'التوقعات التشغيلية',
  dash_forecast_desc: 'توقع زيادة +15% في حجم الطرود الأسبوع القادم (~340 طرد)',
  dash_live_feed_title: 'سجل العمليات والترحيل المباشر',
  dash_live_feed_desc: 'أحدث أحداث الشبكة والترحيل الفوري',
  dash_recent_manifests: 'أحدث بوالص الشحن والمانيفست',
  dash_recent_manifests_desc: 'بيانات التتبع المباشر من منظومة تارجت اللوجستية',
  dash_view_all: 'عرض الكل',
  dash_th_tracking: 'رقم البوليصة ونوع الخدمة',
  dash_th_route: 'مسار الشحنة',
  dash_th_recipient: 'المستلم',
  dash_th_status: 'الحالة',

  // Kinetic Wizard & Edit Mode (Kuwaiti Arabic)
  wizard_title_new: 'إنشاء بوليصة شحن جديدة',
  wizard_title_edit: 'تعديل بيانات بوليصة الشحن والاعتماد',
  wizard_subtitle: 'تحديد مسار الشحن الدولي، تفاصيل الطرود، واختيار تسعيرة الشحن الأفضل.',
  step_origin_sender: 'بيانات الراسل والمصدر',
  step_destination_receiver: 'بيانات المستلم والوجهة',
  step_cargo_parcels: 'الطرود ومحتويات الشحنة',
  step_carrier_rates: 'شركة الشحن والأسعار',
  step_review_dispatch: 'مراجعة وتأكيد الإصدار',
  sender_merchant_name: 'اسم الراسل / التاجر',
  sender_phone: 'رقم هاتف الراسل',
  sender_address: 'عنوان استلام الشحنة (الراسل)',
  receiver_name: 'اسم المستلم بالكامل',
  receiver_phone: 'رقم هاتف المستلم (واتساب)',
  receiver_paci: 'الرقم الآلي للعنوان (PACI)',
  receiver_area: 'المنطقة',
  receiver_block: 'القطعة',
  receiver_street: 'الشارع',
  receiver_building: 'المبنى / القسيمة',
  receiver_floor: 'الدور',
  receiver_unit: 'الشقة / المكتب',
  driver_notes: 'ملاحظات خاصة للمندوب والتسليم',
  parcels_count: 'عدد الطرود',
  package_weight: 'الوزن الإجمالي (كجم)',
  package_dimensions: 'الأبعاد (طول × عرض × ارتفاع سم)',
  declared_value: 'القيمة المصرح عنها للبضاعة (د.ك)',
  cod_amount_label: 'مبلغ التحصيل عند الاستلام (COD / كي نت)',
  dangerous_goods: 'تحتوي على مواد خطرة أو سوائل قابلة للاشتعال',
  select_carrier_title: 'اختر شركة الشحن ونوع الخدمة',
  estimated_transit_time: 'المدة المتوقعة للتسليم',
  shipping_cost: 'تكلفة الشحن',
  total_payable: 'إجمالي المبلغ المستحق',
  btn_next_step: 'الخطوة التالية ←',
  btn_prev_step: '← السابق',
  btn_create_shipment: 'تأكيد وإصدار بوليصة الشحن',
  btn_save_changes: 'حفظ التعديلات',
  btn_approve_shipment: 'اعتماد وترحيل الشحنة للناقل',

  // Shipment Details & Actions (Kuwaiti Arabic)
  details_title: 'تفاصيل بوليصة الشحن',
  timeline_title: 'سجل مراحل التتبع المباشر',
  btn_print_label: 'طباعة بوليصة الشحن',
  btn_download_invoice: 'تحميل الفاتورة PDF',
  btn_send_whatsapp: 'إرسال إشعار واتساب للعميل',
  btn_share_tracking: 'مشاركة رابط التتبع',
  btn_update_status: 'تحديث حالة الشحنة',
  btn_request_location_otp: 'طلب تأكيد موقع المستلم (OTP)',
  otp_modal_title: 'مساعد التحقق من موقع المستلم الآمن',
  otp_modal_desc: 'إرسال رمز OTP لهاتف المستلم لتأكيد الهوية وتحديد العنوان والموقع على الخريطة بدقة.',
  audit_log_title: 'سجل التدقيق والتعديلات التشغيلية',
  audit_log_desc: 'سجل زمني لجميع التعديلات، تحديثات العنوان، والاعتمادات على البوليصة.',

  // Finance Reports & Analytics (Kuwaiti Business Terms)
  rep_cogs_title: 'تكلفة النقل وهامش ربحية الشحنات',
  rep_cogs_desc: 'تحليل هوامش الربح بنظام القيد المزدوج لمقارنة تكلفة الناقل بالجملة مع الإيراد المفوتر.',
  rep_total_revenue: 'إجمالي الإيرادات المفوترة',
  rep_wholesale_cost: 'تكلفة شركة الشحن (تكلفة البضاعة المباعة)',
  rep_net_gross_profit: 'صافي الربح الإجمالي',
  rep_overall_margin: 'هامش الربح الكلي',
  rep_tracking: 'رقم التتبع / البوليصة',
  rep_carrier: 'الناقل',
  rep_date: 'التاريخ',
  rep_customer: 'العميل / المتجر',
  rep_cost: 'تكلفة الجملة',
  rep_revenue: 'الإيراد المفوتر',
  rep_profit: 'الربح الإجمالي',
  rep_margin_pct: 'نسبة الهامش %',
  rep_payment: 'حالة السداد',
  rep_paid: 'مدفوع',
  rep_unpaid: 'غير مدفوع',
  rep_cod_title: 'تسوية تحصيلات المندوب عند الاستلام (COD)',
  rep_cod_desc: 'تتبع المبالغ النقدية المحصلة بواسطة المناديب عند التسليم وتسوية عهدة وخزينة المستودع.',
  rep_unremitted_shipments: 'شحنات COD غير الموردة',
  rep_unremitted_cash: 'مبالغ نقدية غير موردة',
  rep_driver: 'المندوب والسائق',
  rep_cod_amount: 'مبلغ التحصيل (COD)',
  rep_delivery_status: 'حالة التسليم',
  rep_cod_clearing_status: 'حالة توريد الكاش',
  rep_daily_rev_title: 'الإيرادات اليومية والتحصيلات',
  rep_invoiced_charges: 'الرسوم المفوترة',
  rep_payments_collected: 'الدفعات المحصلة',
  rep_client_org_balances: 'أرصدة الشركات والعملاء',
  rep_credit_limit: 'الحد الائتماني',
  rep_current_balance: 'الرصيد الحالي',
  rep_unapplied_cash: 'دفعات غير مسواة',
  rep_fx_title: 'أسعار صرف العملات ومحرك التحويل',
  rep_fx_desc: 'العملة المرجعية الأساسية: الدينار الكويتي (د.ك). تُستخدم للتسوية التلقائية للفواتير، التزامات الناقل، وتقارير الصرف الأجنبي.',
  rep_live_fx_calc: 'حاسبة الصرف المباشرة',
  rep_currency_code: 'رمز العملة',
  rep_currency_name: 'اسم العملة',
  rep_rate_in_kwd: 'السعر بالدينار الكويتي (الوحدة =)',
  rep_kwd_parity: 'تعادل الدينار الكويتي (1 د.ك =)',
  rep_reconciliation_title: 'مطابقة وتسوية فواتير شركات الشحن',
  rep_reconciliation_desc: 'رفع أو لصق فواتير الناقل (DHL، لوجستكس، OTE) لمطابقة تكاليف الجملة وتسجيل قيود التسوية.',
  rep_select_carrier: 'اختر شركة الشحن',
  rep_upload_csv: 'رفع ملف الفاتورة (CSV)',
  rep_audit_btn: 'مطابقة ومراجعة الفواتير',
  rep_auditing: 'جاري المطابقة والمراجعة...',
  rep_paste_csv_title: 'أو الصق بيانات الفاتورة مباشرة',
  rep_carrier_billed: 'إجمالي المطالبة من الناقل',
  rep_internal_cost: 'التكلفة المتوقعة بالنظام',
  rep_cost_variance: 'إجمالي فروق التكلفة',
  rep_discrepancies: 'الفروقات / غير المطابقة',
  rep_post_adjustments: 'تسجيل قيود التسوية المالية',
  rep_posting: 'جاري تسجيل القيود...',
  rep_audit_notes: 'ملاحظات التدقيق',
  rep_tab_profitability: 'تكلفة النقل وهامش الربحية',
  rep_tab_reconciliation: 'مطابقة فواتير الناقل',
  rep_tab_cod: 'تسوية تحصيلات المندوب (COD)',
  rep_tab_revenue: 'الإيرادات والتحصيلات اليومية',
  rep_tab_balances: 'أرصدة الشركات والمؤسسات',
  rep_tab_rates: 'أسعار صرف العملات والتحويل',

  // Shipment Details Sub-components (Kuwaiti Arabic)
  tab_overview: 'نظرة عامة',
  tab_parcels: 'الطرود والمحتويات',
  tab_activity: 'سجل النشاط والتتبع',
  tab_management: 'العمليات والإدارة التشغيلية',
  origin_sender: 'المصدر (الراسل)',
  destination_recipient: 'الوجهة (المستلم)',
  service_type: 'نوع الخدمة',
  current_location: 'الموقع الحالي',
  share_live_location: 'مشاركة الموقع المباشر',
  generated_documents: 'المستندات والوثائق المصدرة',
  target_label: 'بوليصة تارجت',
  system_label_qr: 'بوليصة الشحن مع باركود QR',
  carrier_awb: 'بوليصة الناقل (AWB)',
  commercial_invoice: 'الفاتورة التجارية',
  customs_declaration: 'البيان الجمركي',
  delivery_progress: 'نسبة تقدم التوصيل',
  sales_price: 'سعر البيع',
  cost_price: 'سعر التكلفة',
  pricing_policy_source: 'سياسة التسعير المعتمدة',
  internal_notes: 'ملاحظات داخلية',
  update_location_manually: 'تحديث الموقع يدوياً'
};

export const countryNames = {
  en: {
    KW: 'Kuwait',
    SA: 'Saudi Arabia',
    AE: 'United Arab Emirates',
    QA: 'Qatar',
    BH: 'Bahrain',
    OM: 'Oman',
    EG: 'Egypt',
    JO: 'Jordan',
    US: 'United States',
    GB: 'United Kingdom',
    CN: 'China',
    TR: 'Turkey',
    IN: 'India',
    LB: 'Lebanon',
    IQ: 'Iraq',
    GCC: 'GCC States',
    Kuwait: 'Kuwait',
    'Saudi Arabia': 'Saudi Arabia',
    'United Arab Emirates': 'United Arab Emirates',
    UAE: 'UAE',
    Qatar: 'Qatar',
    Bahrain: 'Bahrain',
    Oman: 'Oman',
    Egypt: 'Egypt',
    Jordan: 'Jordan',
  },
  ar: {
    KW: 'الكويت',
    SA: 'المملكة العربية السعودية',
    AE: 'الإمارات العربية المتحدة',
    QA: 'دولة قطر',
    BH: 'مملكة البحرين',
    OM: 'سلطنة عمان',
    EG: 'جمهورية مصر العربية',
    JO: 'المملكة الأردنية',
    US: 'الولايات المتحدة الأمريكية',
    GB: 'المملكة المتحدة (بريطانيا)',
    CN: 'جمهورية الصين',
    TR: 'تركيا',
    IN: 'الهند',
    LB: 'لبنان',
    IQ: 'العراق',
    GCC: 'دول الخليج العربي',
    Kuwait: 'الكويت',
    'Saudi Arabia': 'السعودية',
    'United Arab Emirates': 'الإمارات',
    UAE: 'الإمارات',
    Qatar: 'قطر',
    Bahrain: 'البحرين',
    Oman: 'عمان',
    Egypt: 'مصر',
    Jordan: 'الأردن',
  }
};

export const cityNames = {
  en: {
    'Kuwait City': 'Kuwait City',
    'Kuwait': 'Kuwait',
    'Shuwaikh': 'Shuwaikh',
    'Hawalli': 'Hawalli',
    'Salmiya': 'Salmiya',
    'Farwaniya': 'Farwaniya',
    'Ahmadi': 'Ahmadi',
    'Jahra': 'Jahra',
    'Riyadh': 'Riyadh',
    'Jeddah': 'Jeddah',
    'Dammam': 'Dammam',
    'Khobar': 'Khobar',
    'Dubai': 'Dubai',
    'Abu Dhabi': 'Abu Dhabi',
    'Sharjah': 'Sharjah',
    'Doha': 'Doha',
    'Manama': 'Manama',
    'Muscat': 'Muscat',
    'Cairo': 'Cairo',
    'Amman': 'Amman',
  },
  ar: {
    'Kuwait City': 'مدينة الكويت',
    'Kuwait': 'الكويت',
    'Shuwaikh': 'الشويخ',
    'Hawalli': 'حولي',
    'Salmiya': 'السالمية',
    'Farwaniya': 'الفروانية',
    'Ahmadi': 'الأحمدي',
    'Jahra': 'الجهراء',
    'Riyadh': 'الرياض',
    'Jeddah': 'جدة',
    'Dammam': 'الدمام',
    'Khobar': 'الخبر',
    'Dubai': 'دبي',
    'Abu Dhabi': 'أبوظبي',
    'Sharjah': 'الشارقة',
    'Doha': 'الدوحة',
    'Manama': 'المنامة',
    'Muscat': 'مسقط',
    'Cairo': 'القاهرة',
    'Amman': 'عمّان',
  }
};

export const translations = {
  en: enTranslations,
  ar: arTranslations
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('target_app_lang') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('target_app_lang', lang);
    const dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.dir = dir;
    document.documentElement.lang = lang;
    
    // Switch primary typography font
    if (lang === 'ar') {
      document.body.style.fontFamily = "'Tajawal', 'Cairo', 'Manrope', sans-serif";
    } else {
      document.body.style.fontFamily = "'Manrope', sans-serif";
    }
  }, [lang]);

  const toggleLanguage = () => {
    setLang(prev => (prev === 'en' ? 'ar' : 'en'));
  };

  const setLanguage = (newLang) => {
    if (newLang === 'en' || newLang === 'ar') {
      setLang(newLang);
    }
  };

  const t = (key, fallback) => {
    const currentDict = translations[lang] || translations.en;
    if (currentDict && currentDict[key] !== undefined) return currentDict[key];
    if (translations.en && translations.en[key] !== undefined) return translations.en[key];
    return fallback !== undefined ? fallback : key;
  };

  const getCountryName = (codeOrName) => {
    if (!codeOrName) return '';
    const dict = countryNames[lang] || countryNames.en;
    return dict[codeOrName] || codeOrName;
  };

  const getCityName = (city) => {
    if (!city) return '';
    const dict = cityNames[lang] || cityNames.en;
    return dict[city] || city;
  };

  const formatRoute = (origin, destination) => {
    const oCity = typeof origin === 'string' ? origin : origin?.city || origin?.countryCode || 'Kuwait';
    const dCity = typeof destination === 'string' ? destination : destination?.city || destination?.countryCode || 'Riyadh';
    const o = getCityName(oCity) || getCountryName(oCity) || oCity;
    const d = getCityName(dCity) || getCountryName(dCity) || dCity;
    const arrow = lang === 'ar' ? '←' : '→';
    return `${o} ${arrow} ${d}`;
  };

  return (
    <LanguageContext.Provider value={{
      lang,
      isRTL: lang === 'ar',
      toggleLanguage,
      setLanguage,
      t,
      getCountryName,
      getCityName,
      formatRoute
    }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export default LanguageContext;
