/**
 * Mock Carrier PDF Document Generator
 * Generates lightweight, compliant PDF data URIs for Waybills and Customs Invoices
 * during local development, test mode, and sandbox carrier simulation.
 */

function createMinimalCarrierPdf(title, trackingNumber, carrier = 'DHL Express', extraDetails = {}) {
    const lines = [
        '%PDF-1.4',
        '1 0 obj <</Type /Catalog /Pages 2 0 R>> endobj',
        '2 0 obj <</Type /Pages /Kids [3 0 R] /Count 1>> endobj',
        '3 0 obj <</Type /Page /Parent 2 0 R /Resources 4 0 R /MediaBox [0 0 595 842] /Contents 5 0 R>> endobj',
        '4 0 obj <</Font <</F1 <</Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold>> /F2 <</Type /Font /Subtype /Type1 /BaseFont /Helvetica>>>>>> endobj'
    ];

    const streamText = [
        'BT',
        `/F1 20 Tf 50 780 Td (${carrier.toUpperCase()} - ${title.toUpperCase()}) Tj`,
        `/F1 14 Tf 0 -30 Td (TRACKING NUMBER / AWB: ${trackingNumber}) Tj`,
        `/F2 10 Tf 0 -25 Td (Generated by Carrier Gateway Service - Official Air Cargo / Customs Document) Tj`,
        `/F2 10 Tf 0 -18 Td (Date: ${new Date().toISOString()}) Tj`,
        `/F2 10 Tf 0 -18 Td (Status: CARRIER DISPATCH CONFIRMED - READY FOR FLIGHT / TRANSIT) Tj`
    ];

    if (extraDetails.origin) {
        streamText.push(`/F2 10 Tf 0 -18 Td (Origin: ${extraDetails.origin}) Tj`);
    }
    if (extraDetails.destination) {
        streamText.push(`/F2 10 Tf 0 -18 Td (Destination: ${extraDetails.destination}) Tj`);
    }
    if (extraDetails.service) {
        streamText.push(`/F2 10 Tf 0 -18 Td (Service: ${extraDetails.service}) Tj`);
    }

    streamText.push(
        `/F1 12 Tf 0 -35 Td (SECURITY & CUSTOMS CLEARANCE MANIFEST) Tj`,
        `/F2 9 Tf 0 -18 Td (This electronic document serves as proof of carrier registration and customs declaration.) Tj`,
        `/F2 9 Tf 0 -14 Td (Authorized carrier barcode verification: |||| ||| ||||| |||| || ||||||) Tj`,
        `ET`
    );

    const streamContent = streamText.join('\n');
    const streamLength = Buffer.byteLength(streamContent, 'utf8');

    lines.push(
        `5 0 obj <</Length ${streamLength}>> stream`,
        streamContent,
        `endstream endobj`,
        `xref`,
        `0 6`,
        `0000000000 65535 f `,
        `0000000010 00000 n `,
        `0000000060 00000 n `,
        `0000000117 00000 n `,
        `0000000219 00000 n `,
        `0000000340 00000 n `,
        `trailer <</Size 6 /Root 1 0 R>>`,
        `startxref`,
        `500`,
        `%%EOF`
    );

    const pdfBuffer = Buffer.from(lines.join('\n'), 'utf8');
    return `data:application/pdf;base64,${pdfBuffer.toString('base64')}`;
}

module.exports = {
    createMinimalCarrierPdf
};
